# Generated by Django 2.2.7 on 2019-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0003_auto_20191027_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
