# Generated by Django 2.2.7 on 2019-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0004_auto_20191107_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expires",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="use_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
