# Generated by Django 3.1.4 on 2020-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0007_coupontype_print_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupontype",
            name="print_template",
            field=models.CharField(
                choices=[("flight", "Flight Coupon"), ("courses", "Courses Coupon")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="coupontype",
            name="validity_cond_text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coupontype",
            name="welcome_text",
            field=models.TextField(null=True),
        ),
    ]
