# Generated by Django 4.2.5 on 2023-09-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_auto_20201213_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontype',
            name='reservation_notes',
            field=models.TextField(null=True),
        ),
    ]
