application: soaring-coupons
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: .*
  script: soaringcoupons.main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
